<?php
require('../psicologo_com_br_backoffice/model/conveniosModel.php');
require('../psicologo_com_br_backoffice/model/dashboardModel.php');
require('../psicologo_com_br_backoffice/model/homeModel.php');
require('../psicologo_com_br_backoffice/model/mensagensModel.php');
require('../psicologo_com_br_backoffice/model/minhaclinicaModel.php');
require('../psicologo_com_br_backoffice/model/profissionaisModel.php');
require('../psicologo_com_br_backoffice/model/quemsomosModel.php');
require('../psicologo_com_br_backoffice/model/workshopsModel.php');
require('../psicologo_com_br_backoffice/model/restritoModel.php');
